name=RUPU
version=1.0.0
author=Kevin
maintainer=Kevin
sentence=Libreria procedural para robot diferencial RUPU.
paragraph=Primera version de la libreria para el robot RUPU. Contiene control PID, telemetría y platooning.
category=Device Control
url=https://github.com
architectures=esp32
includes=RUPU.h
